# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Aserto.Topaz
PackageVersion: 0.30.32
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: topaz.exe
  PortableCommandAlias: topaz
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/aserto-dev/topaz/releases/download/v0.30.32/topaz_windows_x86_64.zip
  InstallerSha256: 5FE5640440FCA729E9F734A594DDE4D2196F121071094E9FF9AD9EFE6F17CE75
ManifestType: installer
ManifestVersion: 1.5.0
