# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Aserto.DSLoad
PackageVersion: 0.30.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ds-load-auth0.exe
  PortableCommandAlias: ds-load-auth0
- RelativeFilePath: ds-load-azuread.exe
  PortableCommandAlias: ds-load-azuread
- RelativeFilePath: ds-load-cognito.exe
  PortableCommandAlias: ds-load-cognito
- RelativeFilePath: ds-load-google.exe
  PortableCommandAlias: ds-load-google
- RelativeFilePath: ds-load-ldap.exe
  PortableCommandAlias: ds-load-ldap
- RelativeFilePath: ds-load-okta.exe
  PortableCommandAlias: ds-load-okta
- RelativeFilePath: ds-load.exe
  PortableCommandAlias: ds-load
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/aserto-dev/ds-load/releases/download/v0.30.3/ds-load_0.30.3_windows_x86_64.zip
  InstallerSha256: C1E7C3EB617518B697420FB3986271075512781B376422E1E41925FEAD2DEF17
ManifestType: installer
ManifestVersion: 1.5.0
ReleaseDate: 2024-01-10
